
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Registro De Citas      <small><?= cclang('detail', ['Registro De Citas']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tmp_cita'); ?>">Registro De Citas</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Registro De Citas</h3>
                     <h5 class="widget-user-desc">Detail Registro De Citas</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tmp_cita" id="form_tmp_cita" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">IdCita </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->idCita); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nombre </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->nombre); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Apellido </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->apellido); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Correo </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->correo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Teléfono </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->telefono); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Marca </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->marca); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Modelo </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->modelo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Placas </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->placas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fecha </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->fecha); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Observaciones </label>

                        <div class="col-sm-8">
                           <?= _ent($tmp_cita->observacioes); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tmp_cita_update', function() use ($tmp_cita){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tmp_cita (Ctrl+e)" href="<?= site_url('administrator/tmp_cita/edit/'.$tmp_cita->idCita); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tmp Cita']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tmp_cita/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tmp Cita']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
