
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Clientes      <small><?= cclang('detail', ['Clientes']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/clientes'); ?>">Clientes</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Clientes</h3>
                     <h5 class="widget-user-desc">Detail Clientes</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_clientes" id="form_clientes" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">IdPersona </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->IdPersona); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nombre </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Nombre); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Apellidos </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Apellidos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alcaldia </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Alcaldia); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CP </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->CP); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Colonia </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Colonia); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Calle </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Calle); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Numero </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Numero); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Telefono </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Telefono); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Correo </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Correo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RFC </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->RFC); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cumple </label>

                        <div class="col-sm-8">
                           <?= _ent($clientes->Cumple); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('clientes_update', function() use ($clientes){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit clientes (Ctrl+e)" href="<?= site_url('administrator/clientes/edit/'.$clientes->IdPersona); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Clientes']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/clientes/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Clientes']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
