
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Cliente      <small><?= cclang('detail', ['Cliente']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/persona'); ?>">Cliente</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Cliente</h3>
                     <h5 class="widget-user-desc">Detail Cliente</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_persona" id="form_persona" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">IdPersona </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->IdPersona); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nombre </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->Nombre); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Apellidos </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->Apellidos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alcaldía </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->alcaldia); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CP </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->cp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Colonia </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->colonia); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Calle </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->calle); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Número </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->numero); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Telefono </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->Telefono); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Correo </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->correo); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RFC </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->RFC); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">IdDireccion </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->IdDireccion); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cumpleaños </label>

                        <div class="col-sm-8">
                           <?= _ent($persona->cumpl); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('persona_update', function() use ($persona){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit persona (Ctrl+e)" href="<?= site_url('administrator/persona/edit/'.$persona->IdPersona); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Persona']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/persona/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Persona']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
